/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhotoRouteImport } from './routes/photo'
import { Route as GlassesRouteImport } from './routes/glasses'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const PhotoRoute = PhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassesRoute = GlassesRouteImport.update({
  id: '/glasses',
  path: '/glasses',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/camera': typeof CameraRoute
  '/glasses': typeof GlassesRoute
  '/photo': typeof PhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/camera': typeof CameraRoute
  '/glasses': typeof GlassesRoute
  '/photo': typeof PhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/camera': typeof CameraRoute
  '/glasses': typeof GlassesRoute
  '/photo': typeof PhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/camera' | '/glasses' | '/photo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/camera' | '/glasses' | '/photo'
  id: '__root__' | '/' | '/auth' | '/camera' | '/glasses' | '/photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CameraRoute: typeof CameraRoute
  GlassesRoute: typeof GlassesRoute
  PhotoRoute: typeof PhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/photo': {
      id: '/photo'
      path: '/photo'
      fullPath: '/photo'
      preLoaderRoute: typeof PhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glasses': {
      id: '/glasses'
      path: '/glasses'
      fullPath: '/glasses'
      preLoaderRoute: typeof GlassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CameraRoute: CameraRoute,
  GlassesRoute: GlassesRoute,
  PhotoRoute: PhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
